export type ListingCondition = 'New' | 'Like New' | 'Good' | 'Fair';
export type ListingCategory =
  | 'Textbooks'
  | 'Electronics'
  | 'Supplies'
  | 'Study Setup'
  | 'Lab Equipment';

export type DemoListing = {
  id: string;
  title: string;
  subtitle: string;
  price: number;
  condition: ListingCondition;
  category: ListingCategory;
  image: string;
  seller: string;
  location: string;
  description?: string;
  createdAt: string;
  isUserListing?: boolean;
};

const LISTINGS_KEY = 'acadex_user_listings';

export const listingCategories: ListingCategory[] = [
  'Textbooks',
  'Electronics',
  'Supplies',
  'Study Setup',
  'Lab Equipment',
];

export const listingConditions: ListingCondition[] = ['New', 'Like New', 'Good', 'Fair'];

const textbookImage = 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=900&q=80';
const electronicsImage = 'https://images.unsplash.com/photo-1517336714739-489689fd1ca8?auto=format&fit=crop&w=900&q=80';
const suppliesImage = 'https://images.unsplash.com/photo-1507842217343-583bb7270b66?auto=format&fit=crop&w=900&q=80';
const studySetupImage = 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=900&q=80';
const labImage = 'https://images.unsplash.com/photo-1581092921461-eab62e97a780?auto=format&fit=crop&w=900&q=80';

export const seedListings: DemoListing[] = [
  {
    id: 'seed-1',
    title: 'Calculus: Early Transcendentals',
    subtitle: 'James Stewart, 8th Edition',
    price: 150,
    condition: 'Good',
    category: 'Textbooks',
    image: textbookImage,
    seller: 'Alya Hassan',
    location: 'Dubai',
    createdAt: '2026-04-30T09:00:00.000Z',
  },
  {
    id: 'seed-2',
    title: 'Apple MacBook Air M1',
    subtitle: '13-inch, 2020',
    price: 2500,
    condition: 'Like New',
    category: 'Electronics',
    image: electronicsImage,
    seller: 'Khaled Omar',
    location: 'Sharjah',
    createdAt: '2026-04-30T08:50:00.000Z',
  },
  {
    id: 'seed-3',
    title: 'Casio fx-991EX ClassWiz Scientific Calculator',
    subtitle: 'Student calculator',
    price: 95,
    condition: 'Good',
    category: 'Supplies',
    image: suppliesImage,
    seller: 'Sara Nabil',
    location: 'Ajman',
    createdAt: '2026-04-30T08:40:00.000Z',
  },
  {
    id: 'seed-4',
    title: 'Rain Design mStand Laptop Stand',
    subtitle: 'Aluminum laptop stand',
    price: 110,
    condition: 'Like New',
    category: 'Study Setup',
    image: studySetupImage,
    seller: 'Mariam Tarek',
    location: 'Abu Dhabi',
    createdAt: '2026-04-30T08:30:00.000Z',
  },
  {
    id: 'seed-5',
    title: 'Elegoo UNO R3 Arduino Starter Kit',
    subtitle: 'Lab and engineering starter set',
    price: 140,
    condition: 'New',
    category: 'Lab Equipment',
    image: labImage,
    seller: 'Yousef Adel',
    location: 'Dubai',
    createdAt: '2026-04-30T08:20:00.000Z',
  },
  {
    id: 'seed-6',
    title: 'Introduction to Algorithms',
    subtitle: 'Cormen et al., 3rd Edition',
    price: 180,
    condition: 'Good',
    category: 'Textbooks',
    image: textbookImage,
    seller: 'Noor Jamal',
    location: 'Al Ain',
    createdAt: '2026-04-30T08:10:00.000Z',
  },
  {
    id: 'seed-7',
    title: 'Apple MacBook Pro M2',
    subtitle: '13-inch, 2022',
    price: 3400,
    condition: 'Like New',
    category: 'Electronics',
    image: electronicsImage,
    seller: 'Hassan Reza',
    location: 'Dubai',
    createdAt: '2026-04-30T08:00:00.000Z',
  },
  {
    id: 'seed-8',
    title: 'Texas Instruments TI-84 Plus Graphing Calculator',
    subtitle: 'Graphing calculator',
    price: 280,
    condition: 'Good',
    category: 'Supplies',
    image: suppliesImage,
    seller: 'Lina Hamed',
    location: 'Sharjah',
    createdAt: '2026-04-30T07:50:00.000Z',
  },
  {
    id: 'seed-9',
    title: 'BenQ WiT MindDuo LED Desk Lamp',
    subtitle: 'Desk lamp for study setup',
    price: 210,
    condition: 'Like New',
    category: 'Study Setup',
    image: studySetupImage,
    seller: 'Farah Khalil',
    location: 'Dubai',
    createdAt: '2026-04-30T07:40:00.000Z',
  },
  {
    id: 'seed-10',
    title: 'AstroAI Digital Multimeter',
    subtitle: 'AM33D model',
    price: 85,
    condition: 'New',
    category: 'Lab Equipment',
    image: labImage,
    seller: 'Omar Hadi',
    location: 'Abu Dhabi',
    createdAt: '2026-04-30T07:30:00.000Z',
  },
  {
    id: 'seed-11',
    title: 'Organic Chemistry',
    subtitle: 'Paula Bruice, 8th Edition',
    price: 135,
    condition: 'Good',
    category: 'Textbooks',
    image: textbookImage,
    seller: 'Reem Bilal',
    location: 'Dubai',
    createdAt: '2026-04-30T07:20:00.000Z',
  },
  {
    id: 'seed-12',
    title: 'Dell XPS 13 9310 Laptop',
    subtitle: 'Student laptop',
    price: 2900,
    condition: 'Good',
    category: 'Electronics',
    image: electronicsImage,
    seller: 'Mahmoud Sami',
    location: 'Ajman',
    createdAt: '2026-04-30T07:10:00.000Z',
  },
  {
    id: 'seed-13',
    title: 'Moleskine Classic Hardcover Notebook',
    subtitle: 'A4 notebook',
    price: 45,
    condition: 'New',
    category: 'Supplies',
    image: suppliesImage,
    seller: 'Dana Wael',
    location: 'Dubai',
    createdAt: '2026-04-30T07:00:00.000Z',
  },
  {
    id: 'seed-14',
    title: 'IKEA Markus Ergonomic Office Chair',
    subtitle: 'Study chair',
    price: 450,
    condition: 'Good',
    category: 'Study Setup',
    image: studySetupImage,
    seller: 'Huda Karim',
    location: 'Sharjah',
    createdAt: '2026-04-30T06:50:00.000Z',
  },
  {
    id: 'seed-15',
    title: 'Engineering Mechanics: Statics',
    subtitle: 'Hibbeler, 14th Edition',
    price: 120,
    condition: 'Fair',
    category: 'Textbooks',
    image: textbookImage,
    seller: 'Salem Tariq',
    location: 'Dubai',
    createdAt: '2026-04-30T06:40:00.000Z',
  },
  {
    id: 'seed-16',
    title: 'HP Spectre x360 14 Convertible Laptop',
    subtitle: 'Convertible laptop',
    price: 3100,
    condition: 'Like New',
    category: 'Electronics',
    image: electronicsImage,
    seller: 'Aya Mostafa',
    location: 'Abu Dhabi',
    createdAt: '2026-04-30T06:30:00.000Z',
  },
  {
    id: 'seed-17',
    title: 'Five Star 3-Subject College Notebook',
    subtitle: 'College notebook',
    price: 30,
    condition: 'New',
    category: 'Supplies',
    image: suppliesImage,
    seller: 'Tala Hussein',
    location: 'Al Ain',
    createdAt: '2026-04-30T06:20:00.000Z',
  },
  {
    id: 'seed-18',
    title: '3M Adjustable Foot Rest',
    subtitle: 'Desk comfort accessory',
    price: 90,
    condition: 'Good',
    category: 'Study Setup',
    image: studySetupImage,
    seller: 'Nora Fares',
    location: 'Dubai',
    createdAt: '2026-04-30T06:10:00.000Z',
  },
  {
    id: 'seed-19',
    title: 'Physics for Scientists and Engineers',
    subtitle: 'Serway and Jewett',
    price: 145,
    condition: 'Good',
    category: 'Textbooks',
    image: textbookImage,
    seller: 'Ahmed Bashir',
    location: 'Sharjah',
    createdAt: '2026-04-30T06:00:00.000Z',
  },
  {
    id: 'seed-20',
    title: 'Lenovo IdeaPad 3',
    subtitle: 'Ryzen 5 model',
    price: 1800,
    condition: 'Good',
    category: 'Electronics',
    image: electronicsImage,
    seller: 'Lujain Salem',
    location: 'Ajman',
    createdAt: '2026-04-30T05:50:00.000Z',
  },
  {
    id: 'seed-21',
    title: 'Stabilo Boss Original Highlighter Set',
    subtitle: '6-pack',
    price: 25,
    condition: 'New',
    category: 'Supplies',
    image: suppliesImage,
    seller: 'Yara Nasr',
    location: 'Dubai',
    createdAt: '2026-04-30T05:40:00.000Z',
  },
  {
    id: 'seed-22',
    title: 'UGREEN Cable Organizer Clips',
    subtitle: 'Desk cable management',
    price: 20,
    condition: 'New',
    category: 'Study Setup',
    image: studySetupImage,
    seller: 'Mohammed Zaki',
    location: 'Fujairah',
    createdAt: '2026-04-30T05:30:00.000Z',
  },
  {
    id: 'seed-23',
    title: 'Discrete Mathematics and Its Applications',
    subtitle: 'Kenneth Rosen',
    price: 110,
    condition: 'Good',
    category: 'Textbooks',
    image: textbookImage,
    seller: 'Safa Rashid',
    location: 'Dubai',
    createdAt: '2026-04-30T05:20:00.000Z',
  },
  {
    id: 'seed-24',
    title: 'Apple iPad Air',
    subtitle: '5th generation with Apple Pencil 2nd gen',
    price: 2300,
    condition: 'Like New',
    category: 'Electronics',
    image: electronicsImage,
    seller: 'Rami Nasser',
    location: 'Abu Dhabi',
    createdAt: '2026-04-30T05:10:00.000Z',
  },
  {
    id: 'seed-25',
    title: 'Pilot G2 Premium Gel Pen Set',
    subtitle: '10-pack',
    price: 35,
    condition: 'New',
    category: 'Supplies',
    image: suppliesImage,
    seller: 'Nadeen Ali',
    location: 'Dubai',
    createdAt: '2026-04-30T05:00:00.000Z',
  },
  {
    id: 'seed-26',
    title: 'Havit HV-F2056 Laptop Cooling Pad',
    subtitle: 'Cooling stand',
    price: 75,
    condition: 'Like New',
    category: 'Study Setup',
    image: studySetupImage,
    seller: 'Basma Khaled',
    location: 'Sharjah',
    createdAt: '2026-04-30T04:50:00.000Z',
  },
  {
    id: 'seed-27',
    title: 'Database System Concepts',
    subtitle: 'Silberschatz, 7th Edition',
    price: 130,
    condition: 'Good',
    category: 'Textbooks',
    image: textbookImage,
    seller: 'Saif Jaber',
    location: 'Al Ain',
    createdAt: '2026-04-30T04:40:00.000Z',
  },
  {
    id: 'seed-28',
    title: 'Samsung Galaxy Tab S7 FE Tablet',
    subtitle: 'Tablet',
    price: 1900,
    condition: 'Good',
    category: 'Electronics',
    image: electronicsImage,
    seller: 'Hiba Omar',
    location: 'Dubai',
    createdAt: '2026-04-30T04:30:00.000Z',
  },
  {
    id: 'seed-29',
    title: 'Post-it Super Sticky Notes',
    subtitle: 'Assorted colors pack',
    price: 20,
    condition: 'New',
    category: 'Supplies',
    image: suppliesImage,
    seller: 'Rana Tamer',
    location: 'Ajman',
    createdAt: '2026-04-30T04:20:00.000Z',
  },
  {
    id: 'seed-30',
    title: 'Lamicall Adjustable Tablet Stand',
    subtitle: 'Tablet stand',
    price: 55,
    condition: 'Like New',
    category: 'Study Setup',
    image: studySetupImage,
    seller: 'Waleed Noor',
    location: 'Dubai',
    createdAt: '2026-04-30T04:10:00.000Z',
  },
  {
    id: 'seed-31',
    title: 'Linear Algebra and Its Applications',
    subtitle: 'David C. Lay',
    price: 115,
    condition: 'Good',
    category: 'Textbooks',
    image: textbookImage,
    seller: 'Haneen Qasim',
    location: 'Sharjah',
    createdAt: '2026-04-30T04:00:00.000Z',
  },
  {
    id: 'seed-32',
    title: 'Apple Magic Keyboard',
    subtitle: 'Bluetooth keyboard',
    price: 260,
    condition: 'Like New',
    category: 'Electronics',
    image: electronicsImage,
    seller: 'Iman Saeed',
    location: 'Dubai',
    createdAt: '2026-04-30T03:50:00.000Z',
  },
  {
    id: 'seed-33',
    title: 'Kokuyo Campus Binder Notebook with Dividers',
    subtitle: 'Binder notebook',
    price: 40,
    condition: 'New',
    category: 'Supplies',
    image: suppliesImage,
    seller: 'Joud Karim',
    location: 'Abu Dhabi',
    createdAt: '2026-04-30T03:40:00.000Z',
  },
  {
    id: 'seed-34',
    title: 'Samsonite Xenon 3.0 Slim Laptop Backpack',
    subtitle: 'Laptop backpack',
    price: 180,
    condition: 'Good',
    category: 'Study Setup',
    image: studySetupImage,
    seller: 'Tariq Hamza',
    location: 'Dubai',
    createdAt: '2026-04-30T03:30:00.000Z',
  },
  {
    id: 'seed-35',
    title: 'Principles of Economics',
    subtitle: 'N. Gregory Mankiw',
    price: 125,
    condition: 'Good',
    category: 'Textbooks',
    image: textbookImage,
    seller: 'Mira Adel',
    location: 'Ajman',
    createdAt: '2026-04-30T03:20:00.000Z',
  },
  {
    id: 'seed-36',
    title: 'Logitech MX Master 3 Wireless Mouse',
    subtitle: 'Wireless mouse',
    price: 240,
    condition: 'Like New',
    category: 'Electronics',
    image: electronicsImage,
    seller: 'Ali Samer',
    location: 'Dubai',
    createdAt: '2026-04-30T03:10:00.000Z',
  },
  {
    id: 'seed-37',
    title: 'Eastpak Padded Pak’r Backpack',
    subtitle: 'Everyday backpack',
    price: 95,
    condition: 'Good',
    category: 'Supplies',
    image: suppliesImage,
    seller: 'Dana Hossam',
    location: 'Sharjah',
    createdAt: '2026-04-30T03:00:00.000Z',
  },
  {
    id: 'seed-38',
    title: 'Human Anatomy & Physiology',
    subtitle: 'Elaine Marieb',
    price: 140,
    condition: 'Good',
    category: 'Textbooks',
    image: textbookImage,
    seller: 'Maha Ehab',
    location: 'Abu Dhabi',
    createdAt: '2026-04-30T02:50:00.000Z',
  },
  {
    id: 'seed-39',
    title: 'Sony WH-1000XM5 Noise Cancelling Headphones',
    subtitle: 'Wireless headphones',
    price: 900,
    condition: 'Like New',
    category: 'Electronics',
    image: electronicsImage,
    seller: 'Nasser Fadi',
    location: 'Dubai',
    createdAt: '2026-04-30T02:40:00.000Z',
  },
  {
    id: 'seed-40',
    title: 'Muji Gel Ink Pen Set',
    subtitle: 'Pen set',
    price: 28,
    condition: 'New',
    category: 'Supplies',
    image: suppliesImage,
    seller: 'Rania Sabri',
    location: 'Al Ain',
    createdAt: '2026-04-30T02:30:00.000Z',
  },
  {
    id: 'seed-41',
    title: 'Apple AirPods Pro',
    subtitle: '2nd generation',
    price: 700,
    condition: 'Like New',
    category: 'Electronics',
    image: electronicsImage,
    seller: 'Fares Mounir',
    location: 'Dubai',
    createdAt: '2026-04-30T02:20:00.000Z',
  },
  {
    id: 'seed-42',
    title: 'Staedtler Noris Club Mechanical Pencil Set',
    subtitle: 'Mechanical pencil set',
    price: 22,
    condition: 'New',
    category: 'Supplies',
    image: suppliesImage,
    seller: 'Lara Hassan',
    location: 'Sharjah',
    createdAt: '2026-04-30T02:10:00.000Z',
  },
  {
    id: 'seed-43',
    title: 'SanDisk Ultra 128GB USB 3.0 Flash Drive',
    subtitle: 'Flash drive',
    price: 55,
    condition: 'New',
    category: 'Electronics',
    image: electronicsImage,
    seller: 'Bader Khalifa',
    location: 'Ajman',
    createdAt: '2026-04-30T02:00:00.000Z',
  },
  {
    id: 'seed-44',
    title: 'Amazon Basics Mesh Desk Organizer',
    subtitle: 'Desk organizer',
    price: 35,
    condition: 'New',
    category: 'Supplies',
    image: suppliesImage,
    seller: 'Yasmin Adel',
    location: 'Dubai',
    createdAt: '2026-04-30T01:50:00.000Z',
  },
  {
    id: 'seed-45',
    title: 'Seagate Portable 1TB External Hard Drive',
    subtitle: 'External storage',
    price: 180,
    condition: 'Good',
    category: 'Electronics',
    image: electronicsImage,
    seller: 'Hatem Rami',
    location: 'Abu Dhabi',
    createdAt: '2026-04-30T01:40:00.000Z',
  },
  {
    id: 'seed-46',
    title: 'Texas Instruments TI-Nspire CX II Calculator',
    subtitle: 'Advanced graphing calculator',
    price: 420,
    condition: 'Good',
    category: 'Supplies',
    image: suppliesImage,
    seller: 'Aseel Hamad',
    location: 'Dubai',
    createdAt: '2026-04-30T01:30:00.000Z',
  },
  {
    id: 'seed-47',
    title: 'ASUS ZenScreen 15.6 Portable Monitor',
    subtitle: 'Portable monitor',
    price: 650,
    condition: 'Like New',
    category: 'Electronics',
    image: electronicsImage,
    seller: 'Karim Saad',
    location: 'Sharjah',
    createdAt: '2026-04-30T01:20:00.000Z',
  },
  {
    id: 'seed-48',
    title: 'Casio fx-CG50 Color Graphing Calculator',
    subtitle: 'Color graphing calculator',
    price: 390,
    condition: 'Good',
    category: 'Supplies',
    image: suppliesImage,
    seller: 'Mona Kamel',
    location: 'Dubai',
    createdAt: '2026-04-30T01:10:00.000Z',
  },
  {
    id: 'seed-49',
    title: 'Anker PowerCore 20000mAh Power Bank',
    subtitle: 'Portable charger',
    price: 150,
    condition: 'Good',
    category: 'Electronics',
    image: electronicsImage,
    seller: 'Rashed Nour',
    location: 'Abu Dhabi',
    createdAt: '2026-04-30T01:00:00.000Z',
  },
  {
    id: 'seed-50',
    title: 'Sharp EL-W516TBSL Advanced Scientific Calculator',
    subtitle: 'Scientific calculator',
    price: 85,
    condition: 'Good',
    category: 'Supplies',
    image: suppliesImage,
    seller: 'Sana Jaber',
    location: 'Ajman',
    createdAt: '2026-04-30T00:50:00.000Z',
  },
];

export function getBadgeClasses(condition: ListingCondition) {
  switch (condition) {
    case 'New':
      return 'bg-blue-100 text-blue-700';
    case 'Like New':
      return 'bg-green-100 text-green-700';
    case 'Good':
      return 'bg-yellow-100 text-yellow-700';
    default:
      return 'bg-red-100 text-red-700';
  }
}

export function getUserListings() {
  const raw = localStorage.getItem(LISTINGS_KEY);

  if (!raw) {
    return [];
  }

  try {
    return JSON.parse(raw) as DemoListing[];
  } catch {
    return [];
  }
}

export function saveUserListing(listing: DemoListing) {
  const existing = getUserListings();
  localStorage.setItem(LISTINGS_KEY, JSON.stringify([listing, ...existing]));
}

export function getAllListings() {
  return [...getUserListings(), ...seedListings].sort(
    (left, right) => new Date(right.createdAt).getTime() - new Date(left.createdAt).getTime(),
  );
}
